name: Build and Deploy Docker Compose

on:
  push:
    branches:
      - main  # Or your preferred branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build and push Docker images (defined in docker-compose.yml)
      - name: Build and push Docker images
        uses: docker/compose@v2
        with:
          file: docker-compose.yml
          push: true
          context: .
          dockerfile: Dockerfile
          target: build
          build-arg: |
            DOCKER_REGISTRY=${{ secrets.DOCKER_REGISTRY }}
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}

      # 4. (Optional) Deploy to a remote server or cloud using Docker Compose
      - name: Deploy Docker Compose stack
        uses: appleboy/ssh-action@v1
        with:
          hostname: your-remote-server.com
          username: your-username
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d